### ISSUE TITLE
`hpack` in the nix-shell is the wrong version

### ISSUE THREAD

**Issue by silky** [marcosh/crem#86]
```
> hpack --version
hpack version 0.34.7
```

But the `package.yaml` has been generated by `0.35.2`; which is the required version, because of the `when` clause things:

```
> hpack
WARNING: package.yaml: Ignoring unrecognized field $.when[0].then.language
crem.cabal was generated with a newer version of hpack, please upgrade and try again.
```

**Comment by marcosh** [comment]
Ah, my bad... locally I'm using the newer version of `hpack`.

It looks like that in the `unstable` channel the `0.35.2` version is already available.

How do I tell Nix to use that?

**Comment by silky** [comment]
I was a bit baffled too; I tried deleting the `flake.lock` to get it to re-grab the latest unstable, but it seems to have not worked; (I got the same version of hpack).

I think through judicious use of `nix why-depends` it's possible to work, but I can't work out the magic invocation to get that telling me something useful:

```
> nix why-depends --derivation .#crem.ghc90 /nix/store/df2cz2rckr5ib0zd0s4sjscwcyrlmi8x-hpack-0.34.7/bin/hpack
/nix/store/phn79wczkzk4g94g10i3jqi0wi65pwvn-crem-0.1.0.0.drv
└───/nix/store/5kwigqn71adzakhb5rhfpgh7k1zs4mqc-hpack-0.34.7.drv
```

**Comment by silky** [comment]
I think it's coming in from a particular version of GHC. I don't know why `why-depends` isn't showing that, though.

**Comment by marcosh** [comment]
> I think it's coming in from a particular version of GHC. I don't know why `why-depends` isn't showing that, though.

On my local machine I'm using `GHC` 9.0.2 with `hpack` 0.35.2... maybe something related to how those things are connected in nixpkgs?
